"""n2nreationship

Revision ID: 565d2c333591
Revises: 75d1b6b02c2f
Create Date: 2021-06-22 22:17:32.165284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565d2c333591'
down_revision = '75d1b6b02c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
